### ISSUE TITLE
Difference from https://gitlab.com/buildroot.org/buildroot

### ISSUE THREAD

**Issue by x3ccd4828** [bootlin/buildroot#1]
What is the difference between this buildroot repo and the one maintained by buildroot.org that can be found at https://gitlab.com/buildroot.org/buildroot? 
Is one a subset of the other or have they diverged moving forward?

**Comment by tpetazzoni** [comment]
https://gitlab.com/buildroot.org/buildroot is a mirror of the official Buildroot repo at https://git.buildroot.org/buildroot/, it is synced very regularly.

This repo (https://github.com/bootlin/buildroot/) is simply Bootlin's fork of Buildroot, which we use to publish some of our work on Buildroot. It is not regularly synced with upstream Buildroot.

**Comment by AndreiCherniaev** [comment]
Can you add this text in GitHub About section? "fork of Buildroot, which we use to publish some of our work on Buildroot. It is not regularly synced with upstream Buildroot."

<img width="500" height="655" alt="Image" src="https://github.com/user-attachments/assets/429d271b-e11d-4b39-9fd8-c92f4e9d20a1" />
