### ISSUE TITLE
Question: Does the STM32MP157 config fits STM32MP151?

### ISSUE THREAD

**Issue by DanielMartensson** [bootlin/buildroot#5]
Hi!

I have build my own STM32MP151 board.
Now I'm looking for a linux OS for that board. Does the STM32MP157 config fits STM32MP151 or do you recommend any OS to that board?

https://github.com/DanielMartensson/STM32-Computer

**Comment by tpetazzoni** [comment]
This is only a fork of Buildroot, not meant to receive issue reports. If you expect to get commercial support from Bootlin, contact us at info@bootlin.com (we are a ST Authorized Partner and can support you in your STM32MP1 Linux projects). If you except free community driven support, contact the Buildroot community through its mailing list or bug tracker. Thanks!
